version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smk-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      chown -R www-data:www-data storage bootstrap/cache storage/framework &&
      chmod -R 775 storage bootstrap/cache storage/framework &&
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      apache2-foreground
      "
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true
