# ✅ Boleh hapus "version" karena sudah deprecated (opsional)
services:
  db:
    image: mysql:5.7
    container_name: laravel-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: smk-bisa
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: smk1sumenep
      MYSQL_PASSWORD: smkbisa
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared
    restart: unless-stopped

volumes:
  db_data:

networks:
  shared:
    name: shared  # <-- ini penting untuk bikin network bisa digunakan antar proyek
